/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Login.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Client.contentsClient;


/**
 *
 * @author 2105247816
 */
public class clientQuestions extends javax.swing.JFrame {
    Connection conn = new DBConnection().connect();
    /**
     * Creates new form createACC */

     public clientQuestions() {
        initComponents();
        idTextField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        firstNLabel = new javax.swing.JLabel();
        lastNLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        contactNoTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        exitButton1 = new javax.swing.JButton();
        passLabel1 = new javax.swing.JLabel();
        passLabel2 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        guardianContactTextField = new javax.swing.JTextField();
        guardianTextField = new javax.swing.JTextField();
        passLabel3 = new javax.swing.JLabel();
        courseTextField = new javax.swing.JTextField();
        industryTextField = new javax.swing.JTextField();
        passLabel4 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(75, 20));
        jPanel1.setMinimumSize(new java.awt.Dimension(75, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(75, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Create An Account");

        userLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel.setText("Contact no");
        userLabel.setMaximumSize(new java.awt.Dimension(75, 20));
        userLabel.setMinimumSize(new java.awt.Dimension(75, 20));
        userLabel.setPreferredSize(new java.awt.Dimension(75, 20));

        passLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLabel.setText("Address:");
        passLabel.setMaximumSize(new java.awt.Dimension(75, 20));
        passLabel.setMinimumSize(new java.awt.Dimension(75, 20));
        passLabel.setPreferredSize(new java.awt.Dimension(75, 20));

        firstNLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstNLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstNLabel.setText("First Name:");
        firstNLabel.setMaximumSize(new java.awt.Dimension(75, 20));
        firstNLabel.setMinimumSize(new java.awt.Dimension(75, 20));
        firstNLabel.setPreferredSize(new java.awt.Dimension(75, 20));

        lastNLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastNLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastNLabel.setText("Last Name:");
        lastNLabel.setMaximumSize(new java.awt.Dimension(75, 20));
        lastNLabel.setMinimumSize(new java.awt.Dimension(75, 20));
        lastNLabel.setPreferredSize(new java.awt.Dimension(75, 20));

        ageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ageLabel.setText("Email:");
        ageLabel.setMaximumSize(new java.awt.Dimension(75, 20));
        ageLabel.setMinimumSize(new java.awt.Dimension(75, 20));
        ageLabel.setPreferredSize(new java.awt.Dimension(75, 20));

        contactNoTextField.setMaximumSize(new java.awt.Dimension(125, 20));
        contactNoTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        contactNoTextField.setPreferredSize(new java.awt.Dimension(125, 25));

        firstNameTextField.setMaximumSize(new java.awt.Dimension(125, 20));
        firstNameTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        firstNameTextField.setPreferredSize(new java.awt.Dimension(125, 25));

        lastNameTextField.setMaximumSize(new java.awt.Dimension(125, 20));
        lastNameTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        lastNameTextField.setPreferredSize(new java.awt.Dimension(125, 25));

        emailTextField.setMaximumSize(new java.awt.Dimension(125, 20));
        emailTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        emailTextField.setPreferredSize(new java.awt.Dimension(125, 25));

        createButton.setText("Create");
        createButton.setPreferredSize(new java.awt.Dimension(90, 20));
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        exitButton1.setText("Exit");
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });

        passLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLabel1.setText("Guardian Name:");
        passLabel1.setMaximumSize(new java.awt.Dimension(75, 20));
        passLabel1.setMinimumSize(new java.awt.Dimension(75, 20));
        passLabel1.setPreferredSize(new java.awt.Dimension(75, 20));

        passLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLabel2.setText("Guardian Contact no:");
        passLabel2.setMaximumSize(new java.awt.Dimension(75, 20));
        passLabel2.setMinimumSize(new java.awt.Dimension(75, 20));
        passLabel2.setPreferredSize(new java.awt.Dimension(75, 20));

        addressTextField.setMaximumSize(new java.awt.Dimension(125, 20));
        addressTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        addressTextField.setPreferredSize(new java.awt.Dimension(125, 25));

        guardianContactTextField.setMaximumSize(new java.awt.Dimension(125, 20));
        guardianContactTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        guardianContactTextField.setPreferredSize(new java.awt.Dimension(125, 25));

        guardianTextField.setMaximumSize(new java.awt.Dimension(125, 20));
        guardianTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        guardianTextField.setPreferredSize(new java.awt.Dimension(125, 25));

        passLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLabel3.setText("Industry:");
        passLabel3.setMaximumSize(new java.awt.Dimension(75, 20));
        passLabel3.setMinimumSize(new java.awt.Dimension(75, 20));
        passLabel3.setPreferredSize(new java.awt.Dimension(75, 20));

        courseTextField.setMaximumSize(new java.awt.Dimension(125, 20));
        courseTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        courseTextField.setPreferredSize(new java.awt.Dimension(125, 25));

        industryTextField.setMaximumSize(new java.awt.Dimension(125, 20));
        industryTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        industryTextField.setPreferredSize(new java.awt.Dimension(125, 25));

        passLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLabel4.setText("Course:");
        passLabel4.setMaximumSize(new java.awt.Dimension(75, 20));
        passLabel4.setMinimumSize(new java.awt.Dimension(75, 20));
        passLabel4.setPreferredSize(new java.awt.Dimension(75, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(284, 284, 284)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(exitButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addComponent(passLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(passLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(83, 83, 83)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(courseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(industryTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(187, 187, 187)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(firstNLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lastNLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(133, 133, 133)
                                            .addComponent(passLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(passLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(83, 83, 83)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(contactNoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(guardianContactTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(guardianTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 540, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardianContactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(industryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exitButton1)
                            .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        String delete = "DELETE * FROM temp";
        try {
        PreparedStatement psDel = conn.prepareStatement(delete);
        psDel.executeQuery();
        } catch (Exception e){}
        System.exit(0);
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
         
        String firstname = firstNameTextField.getText();
        String lastname =  lastNameTextField.getText();
        String email = emailTextField.getText();
        String contactNO = contactNoTextField.getText();
        String address = addressTextField.getText();
        String guardian =  guardianTextField.getText();
        String guardianContact = guardianContactTextField.getText();
        String industry = industryTextField.getText();
        String course = courseTextField.getText();
        
        
        if(email.equals("") | contactNO.equals("") | firstname.equals("") | lastname.equals("") | address.equals("") | guardian.equals("") | guardianContact.equals("") | industry.equals("") | course.equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill All Fields");
        } else {

        
        String query = "UPDATE userclient SET email=?,contactNo=?,address=?,guardianName=?,guardianContact=? WHERE firstname=? and lastname=?";
            try {
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setString(1, email);
                ps.setString(2, contactNO);
                ps.setString(3, address);
                ps.setString(4, guardian);
                ps.setString(5, guardianContact);
                ps.setString(6, firstname);
                ps.setString(7, lastname);
                ps.executeUpdate();
                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "done1");
                    
                    String sql = "Select * From userclient Where firstname=? And lastname=?";
                    try {
                        PreparedStatement ps2 = conn.prepareStatement(sql);
                        ps2.setString(1, firstname);
                        ps2.setString(2, lastname);
                        ResultSet rs2 = ps2.executeQuery();
                        if (rs2.next()) {
                            String ID = rs2.getString("id");
                            idTextField.setText(ID);
                            
                            JOptionPane.showMessageDialog(null, "done2");
                            
                            String sqlquery = "INSERT INTO clientcoursedata(industry, course, clientID) VALUES(?, ?, ?)";
                try {
                    PreparedStatement pst = conn.prepareStatement(sqlquery);
                    pst.setString(1, industry);
                    pst.setString(2, course);
                    pst.setInt(3, Integer.parseInt(idTextField.getText()));

                    pst.executeUpdate();
                    if (pst.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "done3");
                    
                    this.dispose();
                    contentsClient Frame = new contentsClient();
                    Frame.setVisible(true);
                    }
                }
                catch (Exception e){}
                        }
                    }
                    catch (Exception e){} 
                }
            } catch (Exception e){}
            
             
            
            
       

        
        }       
     
    }//GEN-LAST:event_createButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientQuestions().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField contactNoTextField;
    private javax.swing.JTextField courseTextField;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton exitButton1;
    private javax.swing.JLabel firstNLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField guardianContactTextField;
    private javax.swing.JTextField guardianTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JTextField industryTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel passLabel1;
    private javax.swing.JLabel passLabel2;
    private javax.swing.JLabel passLabel3;
    private javax.swing.JLabel passLabel4;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
